### ISSUE TITLE
ValidatablePickerControl

### ISSUE THREAD

**Issue by dooie** [james-russo/XamarinForms-UnobtrusiveValidationPlugin#10]
Hey,

I am trying to extend the functionality to include a validatablePickerControl. I have this largely working except i cannot pass through the ItemDisplayBinding from the xaml. Below is some code snippets. Any pointers greatly appreciated.

        public static BindableProperty ItemDisplayBindingProperty = BindableProperty.Create(
            nameof(ItemDisplayBinding),
            typeof(BindingBase),
            typeof(ValidatablePicker));

        public BindingBase ItemDisplayBinding
        {
            get => _picker.ItemDisplayBinding;
            set => _picker.ItemDisplayBinding = value;
        }
        /// <summary>
        /// </summary>
        public ValidatablePicker()
        {
            _picker.BindingContext = this;
            _picker.SetBinding(Picker.ItemsSourceProperty, nameof(ItemsSource));
            _picker.SetBinding(Picker.TitleProperty, nameof(Title));
            _picker.SetBinding(Picker.SelectedIndexProperty, nameof(SelectedIndex));

            _picker.ItemDisplayBinding = ItemDisplayBinding;

            Children.Add(_picker);

            _errorLabel.SetBinding(IsVisibleProperty, nameof(IsInValid));
            _errorLabel.SetBinding(Label.TextProperty, nameof(Message));
            _errorLabel.BindingContext = this;
            _errorLabel.TextColor = Color.Red;

            Children.Add(_errorLabel);
        }

                        <controls:ValidatablePicker
                    SelectedIndex="{Binding Model.TypeSelectedIndex, Mode=TwoWay}"
                    ItemsSource="{Binding AssetTypes}"
                    ItemDisplayBinding="{Binding Description}"
                    BindingName="AssetTypeId"
                    Title="Select asset type"
                    />

**Comment by james-russo** [comment]
Hey @dooie,

Hard to tell without the full sample of ValidatabalePicker, but at first glance I think that the _ItemDisplayBinding_ should look something like:

`public BindingBase ItemDisplay
        {
            get
            {
                return (BindingBase)GetValue(ItemDisplayProperty);
            }
            set
            {
                SetValue(ItemDisplayProperty, value);
            }
        }`

Then in the constructor you'd use the "SetBinding" method from "_picker" as the other three declarations. 

If that doesn't work, I'll try to recreate the scenario locally in the next few day(s).

**Comment by dooie** [comment]
> Hey @dooie,
> 
> Hard to tell without the full sample of ValidatabalePicker, but at first glance I think that the _ItemDisplayBinding_ should look something like:
> 
> `public BindingBase ItemDisplay { get { return (BindingBase)GetValue(ItemDisplayProperty); } set { SetValue(ItemDisplayProperty, value); } }`
> 
> Then in the constructor you'd use the "SetBinding" method from "_picker" as the other three declarations.
> 
> If that doesn't work, I'll try to recreate the scenario locally in the next few day(s).

Yeah, 'SetBinding' only works on the static bindable properties of the picker. ItemDisplayBinding is simply a public BindingBase property?

**Comment by james-russo** [comment]
@dooie For my own knowledge, I'm going to dig into why they decided to not make that a bindable property.  My guess is that is has something to do with the order of operations for Android vs Apple. 

Nevertheless, I managed to find a solution that doesn't involve extending the current _Picker_ or creating a custom renderer:
1.) Add an optional parameter to your control as a _string_
`public ValidatablePicker(string itemDisplay = "") {
...
}`

2.) Set the property to a new Binding with the value from constructor.
`
_picker.ItemDisplayBinding = new Binding(itemDisplay);
`

3.) In Xaml, pass the value you want using _x:Arguments_ like so:

`<custom:ValidatablePicker ItemsSource="{Binding Source}">
<x:Arguments>
                    <x:String>Name</x:String> <--- "Description" would go here
                </x:Arguments>
 </custom:ValidatablePicker>
`

**Comment by james-russo** [comment]
@dooie Another solution I found thanks to this [Xamarin Forum](https://forums.xamarin.com/discussion/66026/use-attached-bindable-property-in-xaml) would be the following:

1. Change 

 ``` 
public static BindableProperty ItemDisplayBindingProperty = BindableProperty.Create(
         nameof(ItemDisplayBinding),
         typeof(BindingBase),
         typeof(ValidatablePicker));
```
to


```
public static BindableProperty ItemDisplayBindingProperty = BindableProperty.CreateAttached(
        "ItemDisplayBinding",
        typeof(string),
        typeof(ValidatablePicker),
        default(string),
        BindingMode.OneWay,
        propertyChanged: (bindable, oldValue, newValue) =>
        {
            var vp = (ValidatablePicker)bindable;
            vp._picker.ItemDisplayBinding = new Binding(newValue.ToString());
        });
```
**Notice that I've changed the Create to CreateAttached**.  Also, I've added the setting of the _ItemDisplayBinding_ in the propertyChanged event that occurs. 

2. In the XAML you would then just set the property to whatever string you want, for example:

`
<custom:ValidatablePicker ItemsSource="{Binding Source}" ItemDisplay="Description" />
`

3. Remove the following:

```
    public BindingBase ItemDisplayBinding
    {
        get => _picker.ItemDisplayBinding;
        set => _picker.ItemDisplayBinding = value;
    }
````

**Comment by dooie** [comment]
> @dooie Another solution I found thanks to this [Xamarin Forum](https://forums.xamarin.com/discussion/66026/use-attached-bindable-property-in-xaml) would be the following:
> 
> 1. Change
> 
> ```
> public static BindableProperty ItemDisplayBindingProperty = BindableProperty.Create(
>         nameof(ItemDisplayBinding),
>         typeof(BindingBase),
>         typeof(ValidatablePicker));
> ```
> to
> 
> ```
> public static BindableProperty ItemDisplayBindingProperty = BindableProperty.CreateAttached(
>         "ItemDisplayBinding",
>         typeof(string),
>         typeof(ValidatablePicker),
>         default(string),
>         BindingMode.OneWay,
>         propertyChanged: (bindable, oldValue, newValue) =>
>         {
>             var vp = (ValidatablePicker)bindable;
>             vp._picker.ItemDisplayBinding = new Binding(newValue.ToString());
>         });
> ```
> **Notice that I've changed the Create to CreateAttached**. Also, I've added the setting of the _ItemDisplayBinding_ in the propertyChanged event that occurs.
> 
> 1. In the XAML you would then just set the property to whatever string you want, for example:
> 
> `<custom:ValidatablePicker ItemsSource="{Binding Source}" ItemDisplay="Description" />`
> 
> 1. Remove the following:
> 
> ```
>     public BindingBase ItemDisplayBinding
>     {
>         get => _picker.ItemDisplayBinding;
>         set => _picker.ItemDisplayBinding = value;
>     }
> ```

@james-russo Works a treat, thank you!

**Comment by james-russo** [comment]
@dooie my pleasure!  If you feel like it, feel free to create a PR for the control and we'll get reviewed and merged in for others! :)

**Comment by dooie** [comment]
> @dooie my pleasure! If you feel like it, feel free to create a PR for the control and we'll get reviewed and merged in for others! :)

Ill look to do a pull over the weekend

**Comment by mhamel** [comment]
Full exemple since it take me two hours to figure this out once I've read this article.

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="PGEN.Maui.Controls.CustomPicker"
             xmlns:local="clr-namespace:PIF.Maui.Converters"
             x:Name="thisContentView">
    <ContentView.Resources>
        <local:ErrorMessageToUnderlineColorConverter x:Key="errorMessageToUnderlineColorConverter" />
    </ContentView.Resources>

    <StackLayout BindingContext="{x:Reference thisContentView}"
            Orientation="Vertical"
            HorizontalOptions="Center"
            VerticalOptions="Center"
            WidthRequest="{Binding WidthRequest, FallbackValue='300'}">

        <Picker x:Name="MyPicker" Title="{Binding Title}"
                Style="{StaticResource PickerForm}"
                ItemsSource="{Binding ItemsSource}" 
                SelectedItem="{Binding SelectedItem}"
                ItemDisplayBinding="{Binding ItemDisplayBinding}"
                HorizontalOptions="FillAndExpand" />
        
        <Line BackgroundColor="{Binding IsNotValidMessage, Converter={StaticResource errorMessageToUnderlineColorConverter}}" 
              HeightRequest="2" 
              HorizontalOptions="FillAndExpand"  />
        
        <Label TextColor="Red" 
               FontAttributes="Bold" 
               Text="{Binding IsNotValidMessage}" 
               MinimumHeightRequest="20" 
               HeightRequest="25" 
               HorizontalOptions="FillAndExpand"  />
        
    </StackLayout>
</ContentView>
```

```
using System.Collections;

namespace PIF.Maui.Controls
{
    public partial class CustomPicker : ContentView
    {
        public static readonly BindableProperty TitleProperty = BindableProperty.Create(
            nameof(Title),
            typeof(string),
            typeof(CustomPicker),
            null,
            propertyChanging: OnTitleChange,
            propertyChanged: OnTitleChanged);

        public static readonly BindableProperty ItemDisplayBindingProperty = BindableProperty.CreateAttached(
            nameof(ItemDisplayBinding), 
            typeof(string), 
            typeof(CustomPicker),
            default(string), 
            defaultBindingMode: BindingMode.TwoWay, 
            propertyChanging: OnItemDisplayBindingChange,
            propertyChanged: OnItemDisplayBindingChanged);

        public static readonly BindableProperty ItemsSourceProperty = BindableProperty.Create(
            nameof(ItemsSource), 
            typeof(IList), 
            typeof(CustomPicker), 
            null, 
            propertyChanging: OnItemsSourceChange,
            propertyChanged: OnItemsSourceChanged);

        public static readonly BindableProperty SelectedItemProperty = BindableProperty.CreateAttached(
            nameof(SelectedItem),
            typeof(object),
            typeof(CustomPicker),
            null,
            defaultBindingMode: BindingMode.TwoWay,
            propertyChanging: OnSelectedItemChange,
            propertyChanged: OnSelectedItemChanged);

        public static readonly BindableProperty IsNotValidMessageProperty = BindableProperty.Create(
            nameof(IsNotValidMessage),
            typeof(string),
            typeof(CustomPicker),
            null,
            propertyChanging: OnIsNotValidMessageChange,
            propertyChanged: OnIsNotValidMessageChanged);

        public string Title
        {
            get => (string)GetValue(TitleProperty);
            set => SetValue(TitleProperty, value);
        }

        public string IsNotValidMessage
        {
            get => (string)GetValue(IsNotValidMessageProperty);
            set => SetValue(IsNotValidMessageProperty, value);
        }

        public object SelectedItem
        {
            get => (object)GetValue(SelectedItemProperty);
            set => SetValue(SelectedItemProperty, value);
        }

        public string ItemDisplayBinding
        {
            get => (string)GetValue(ItemDisplayBindingProperty);
            set => SetValue(ItemDisplayBindingProperty, value);
        }

        public IList ItemsSource
        {
            get => (IList)GetValue(ItemsSourceProperty);
            set => SetValue(ItemsSourceProperty, value);
        }

        public CustomPicker()
        {
            InitializeComponent();
        }

        static void OnItemDisplayBindingChange(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
           //((ItemDisplayBindingBox)bindable).IsValid = (bool)newValue;
        }

        static void OnItemDisplayBindingChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
            var vp = (CustomPicker)bindable;
            vp.MyPicker.ItemDisplayBinding = new Binding(newValue.ToString());
            //((ItemDisplayBindingBox)bindable).IsValid = (bool)newValue;
        }

        static void OnItemsSourceChange(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
            //((ItemDisplayBindingBox)bindable).ItemsSource = (string)newValue;
        }

        static void OnItemsSourceChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
            //((ItemDisplayBindingBox)bindable).ItemsSource = (string)newValue;
        }

        static void OnSelectedItemChange(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
            //((ItemDisplayBindingBox)bindable).SelectedItem = (string)newValue;
        }

        static void OnSelectedItemChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
            //((ItemDisplayBindingBox)bindable).SelectedItem = (string)newValue;
        }

        static void OnTitleChange(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
            //((ItemDisplayBindingBox)bindable).Title = (string)newValue;
        }

        static void OnTitleChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
            //((ItemDisplayBindingBox)bindable).Title = (string)newValue;
        }
        static void OnIsNotValidMessageChange(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
            //((ItemDisplayBindingBox)bindable).IsNotValidMessage = (string)newValue;
        }

        static void OnIsNotValidMessageChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var s = "";
            //((ItemDisplayBindingBox)bindable).IsNotValidMessage = (string)newValue;
        }
    }
}

```
