### ISSUE TITLE
Placeholder attribute not supported

### ISSUE THREAD

**Issue by fm698** [james-russo/XamarinForms-UnobtrusiveValidationPlugin#6]
I cant put place holder with ValidatableEntryControl

**Comment by james-russo** [comment]
@fm698 Can you provide more detail.  The **Control** property of type _Entry_ is publicly visible with ValidatableEntryControl, therefore you have full access from the code behind.

**Comment by fm698** [comment]
Yes there is no ability to bind from xaml,
but i used the source code and i added the placeholder to the ValidatableEntryControl
