### ISSUE TITLE
The plugin is not compatible with the latest release of FluentValidation Plugin

### ISSUE THREAD

**Issue by fm698** [james-russo/XamarinForms-UnobtrusiveValidationPlugin#9]
When i use the source code instead of install the library from nuget, i find that The plugin is not compatible with the latest release of FluentValidation Plugin,
The maximum version of fluentvalidation allowed is 7.1.1

**Comment by james-russo** [comment]
That is correct. Due to FluentValidation 8.0.0 there was a breaking change that occurred.  I am currently working on updating the project to support the latest version of Fluent.

**Comment by fm698** [comment]
Thank you

**Comment by fm698** [comment]
Is there any plans to update the plugin to support validation behaviors ? 
it will be a great update, and it will be the best plugin for validation with fluent validation latest library and behaviors support

**Comment by dooie** [comment]
Hey, 

Great plugin works a treat for me on Android.

I get the following build error with linking turned on;

error MT2101: Can't resolve the reference 'System.Boolean FluentValidation.ValidatorOptions::get_DisableAccessorCache()', referenced from the method 'FluentValidation.IRuleBuilderInitial`2<T,TType> TPMobile.Forms.Components.Core.Validation.EnhancedAbstractValidator`1::RuleForProp(System.Linq.Expressions.Expression`1<System.Func`2<T,TPMobile.Forms.Components.Core.Validation.ValidatableProperty`1<TType>>>)' in 'FluentValidation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0'.

It's a linking issue i am assuming but I cannot for the life of me resolve it; ive tried skipping the Fluent dll in the Additional Mono args

**Comment by james-russo** [comment]
@dooie I suspect that was due to some of the changes on the FluentValidation side, versus what this package was supporting.  I'd suggest trying the newest version of this plugin (3.0.61) to see if you still have the issue.
